### ISSUE TITLE
Support for `delete`/`insert`/`where` syntax

### ISSUE THREAD

**Issue by aaj3f** [fluree/http-api-gateway#55]
## Description

Whereas `db` resolves any map with `:delete` & `:where` keys (or `:delete`, `:insert`, `:where`) as a unique deletion syntax, `http-api-gateway` seems to treat the following as an insertion of a blank node with two key-value pairs `delete`, and `where`

```json
{
    "ledger": "cookbook/base",
    "txn": {
        "delete": ["ex:mosquitos", "?p", "?o"],
        "where": [["ex:mosquitos", "?p", "?o"]]
    }
}
```
(although, admittedly, it throws an understandable spec error because it can't resolve an array of array values in an insertion)

If useful for development/testing, here are the ledger creation and deletion attempts I've been testing with:
`1. /create`
```json
{
    "ledger": "cookbook/base",
    "defaultContext": {
        "id": "@id",
        "type": "@type",
        "xsd": "http://www.w3.org/2001/XMLSchema#",
        "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
        "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
        "sh": "http://www.w3.org/ns/shacl#",
        "schema": "http://schema.org/",
        "skos": "http://www.w3.org/2008/05/skos#",
        "wiki": "https://www.wikidata.org/wiki/",
        "f": "https://ns.flur.ee/ledger#",
        "ex": "http://example.org/"
    },
    "txn": {
        "@graph": [
            {
                "@id": "ex:fluree",
                "@type": "schema:Organization",
                "schema:description": "We ❤️ Data"
            },
            {
                "@id": "ex:w3c",
                "@type": "schema:Organization",
                "schema:description": "We ❤️ Internet"
            },
            {
                "@id": "ex:mosquitos",
                "@type": "ex:Monster",
                "schema:description": "We ❤️ Human Blood"
            }
        ]
    }
}
```

`2. /transact -- delete a particular fact on a particular subject`
```json
{
    "ledger": "cookbook/base",
    "txn": {
        "delete": ["ex:mosquitos", "schema:description", "?o"],
        "where": [["ex:mosquitos", "schema:description", "?o"]]
    }
}
```

`3. /transact -- delete all facts on a particular subject`
```json
{
    "ledger": "cookbook/base",
    "txn": {
        "delete": ["ex:mosquitos", "?p", "?o"],
        "where": [["ex:mosquitos", "?p", "?o"]]
    }
}
```

`4. /transact -- delete all subjects with a particular value on a particular property`
```json
{
    "ledger": "cookbook/base",
    "txn": {
        "delete": ["?s", "?p", "?o"],
        "where": [["?s", "type", "schema:Organization"]]
    }
}
```

`5. /transact -- delete all subjects with a particular property`
```json
{
    "ledger": "cookbook/base",
    "txn": {
        "delete": ["?s", "?p", "?o"],
        "where": [["?s", "schema:description", "?o"]]
    }
}
```

**Comment by cap10morgan** [comment]
@aaj3f This is hopefully fixed now. Let me know if not!

**Comment by aaj3f** [comment]
@cap10morgan -- using the new `main` of `http-api-gateway`, I still get the following error when submitting the following transaction:
```json
{
    "ledger": "cookbook/base",
    "txn": {
        "delete": ["ex:mosquitos", "schema:description", "?o"],
        "where": [["ex:mosquitos", "schema:description", "?o"]]
    }
}

// =>

{
    "error": "json-ld/invalid-context",
    "idx": [
        "where",
        0
    ],
    "message": "Json-ld sequential values within sequentialvalues is not allowed. Provided value: [[\"ex:mosquitos\" \"schema:description\" \"?o\"]] at index: [\"where\" 0]."
}
```

**Comment by cap10morgan** [comment]
@aaj3f Wuuuuuuuuuuut? That's super weird. I'll look into it.

**Comment by aaj3f** [comment]
@cap10morgan I'm just double-checking really quickly that it wasn't a foolish docker build/run issue on my end
